# Generated by Django 4.2.5 on 2023-09-26 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterOrganisasi',
            fields=[
                ('id_organisasi', models.AutoField(primary_key=True, serialize=False)),
                ('kode_organisasi', models.CharField(default='none', max_length=225)),
                ('urai', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(default=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('hak_akses', models.CharField(default='pegawai', max_length=30)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', to='auth.group')),
                ('id_organisasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sppd.masterorganisasi')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
