# Generated by Django 4.2.5 on 2023-09-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sppd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=225)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MasterLokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_lokasi', models.CharField(max_length=225)),
                ('urai', models.TextField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=225)),
                ('nama', models.CharField(max_length=225)),
                ('golongan', models.CharField(max_length=225)),
                ('no_hp', models.CharField(max_length=225)),
                ('eselon', models.CharField(max_length=225)),
                ('alamat', models.CharField(max_length=225)),
                ('pangkat', models.TextField(max_length=225)),
                ('email', models.EmailField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MasterTahun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=4)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MasterPengesah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rek', models.TextField(max_length=225)),
                ('nama_bank', models.TextField(max_length=225)),
                ('status', models.BooleanField(default=False)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sppd.masterjabatan')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sppd.masterpegawai')),
            ],
        ),
    ]
