# Generated by Django 4.2.5 on 2023-09-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterJabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=225)),
                ('status', models.BooleanField(default=False, max_length=1)),
            ],
        ),
    ]
