# Generated by Django 4.2.4 on 2023-09-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterLokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kd_lokasi', models.CharField(max_length=225)),
                ('urai', models.TextField(max_length=225)),
            ],
        ),
    ]
